### ISSUE TITLE
Deviating module version AzApiCall version 1.1.83

### ISSUE THREAD

**Issue by mwildenb** [Azure/Azure-Governance-Visualizer#23]
When running the AzGovVizParallel.ps1 script it fails with a `'AzAPICall 1.1.83' not installed`. I have a newer version 1.1.84 installed of the AzApiCall module. It asks me to upgrade, but fails (as there is a newer version available).

OUTPUT:

```
'Start Azure Governance Visualizer 10-Nov-2023 09:31:13 (#6.3.3)
Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[3] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.3.9
  PS Version check succeeded
Output/Files will be created in path 'C:\GitHub\Azure-Governance-Visualizer\pwsh\.'
 Verify 'AzAPICall' (1.1.83)
  AzAPICall - Deviating module version 1.1.84
  'AzAPICall 1.1.83' not installed'
```

Windows 11

**AzGovViz version**
please only report bug if you are running the latest version of AzGovViz

**CodeRunPlatform**
Console

**Comment by JulianHayward** [comment]
@mwildenb thanks for reporting; filing a fix for console (user) runs to allow execution with newer versions of the AzAPICall module.

**Comment by mwildenb** [comment]
much appreciated

**Comment by JulianHayward** [comment]
@mwildenb should be good with [6.3.4](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/releases/tag/6.3.4)

closing
