### ISSUE TITLE
critical error in script

### ISSUE THREAD

**Issue by ksagala** [Azure/Azure-Governance-Visualizer#27]
**AzGovViz version**
atest version of AzGovViz 6.3.7

**CodeRunPlatform**
local desktop posh shell 7.4.1

**Describe the bug**
When I execute the script, I have an error and script finish without any data exported:

0 'Available Private Endpoint Types' - Please use another Subscription for the AzContext (current subscriptionId: 'xxx') -> use parameter: -SubscriptionId4AzContext '<subscriptionId>'
Exception: C:\Scripts\AzureGovWiz\AzGovVizParallel.ps1:34266
 Line   |
34266 |              Throw $throwmsg
           |              ~~~~~~~~~~~~~~~
           | 0 'Available Private Endpoint Types' - Please use another Subscription for the AzContext (current
           | subscriptionId: '029cb112-892a-4684-9bf3-6a000a0bc1c1') -> use parameter: -SubscriptionId4AzContext
           | '<subscriptionId>'

**Comment by jtracey93** [comment]
@JulianHayward can you advise?

**Comment by JulianHayward** [comment]
@ksagala please proceed as per the output:

<img width="473" alt="image" src="https://github.com/Azure/Azure-Governance-Visualizer/assets/45695032/2c89da32-16ae-4327-8e0a-fce889720dba">

parameters [ref](https://github.com/julianhayward/azure-mg-sub-governance-reporting?tab=readme-ov-file#parameters)

Example: 
```PowerShell
.\pwsh\azgovvizparallel.ps1 -SubscriptionId4AzContext 'GUID-of-the-subscription'
```

You may also check if/that the resource provider `microsoft.network` is registered for the subscription

**Comment by jtracey93** [comment]
@ksagala did this resolve it for you?

**Comment by ksagala** [comment]
Thanks for your advice, with -SubscriptionId4AzContext  script works properly for me.
