### ISSUE TITLE
Customer needs RBAC details in Azure environment

### ISSUE THREAD

**Issue by amjoneja** [Azure/Azure-Governance-Visualizer#47]
Firstly, I would like to say a big Thank You to all the contributors of this script.
It is a big time help for many scenarios. I have used it 4 times till now.

For one of my customer, where they want the details of RBAC on every scope within the tenant. Th limit with the no. of rows in RBAC Role Assignments is creating issue. Due to this, the required table format is not achievable. 

I have attached the RBAC limit snippet and required table format snippet. 

Kindly help me on the same. 

![Image](https://github.com/user-attachments/assets/61044aae-2df8-497c-abfe-e0006db22311)

![Image](https://github.com/user-attachments/assets/87c90bfc-3b6a-4a2e-9324-2a0da635fe8a)

**Comment by JulianHayward** [comment]
Hello @amjoneja 

you have a couple of options:
* work with the csv output
* use parameter `-HtmlTableRowsLimit 30000`
* use parameter `-RBACAtScopeOnly`

see [parameters](https://github.com/Azure/Azure-Governance-Visualizer?tab=readme-ov-file#parameters) documentation
